CREATE DATABASE IF NOT EXISTS master_of_music_db;
USE master_of_music_db;

INSERT INTO questions (id, question, game_id)
VALUES (1,'Which famous music group were formerly known as the New Yardbirds?', 3),
       (2, 'Who is the lead singer of Pearl Jam?', 3),
       (3, 'The Grateful Dead’s highly-devoted fanbase are known as what?', 3),
       (4,'Which band has the single most sold album of all time?', 3),
       (5, 'Who released the album "Nevermind" in 1991?', 3),
       (6, 'The characters Tommy and Gina feature in which two Bon Jovi singles?', 3),
       (7, 'In Don McLean’s American Pie, “the day the music died” refers to the plane crash that killed Richie Valens, The Big Bopper and which other pioneer of rock and roll?', 3),
       (8, 'Which band formed in Syndey, was started by the brothers Angus and Malcolm Young?', 3),
       (9, 'What is the original name of American rock musician Alice Cooper?', 3),
       (10, 'Name the heavy metal band that was formed by guitarist James Hetfield and drummer Lars Ulrich in 1981.', 3),
       (11, 'Name the rock band that was originally named after basketball player Mookie Blaylock?', 3),
       (12, 'For which track, the Australian rock band AC/DC received their first Grammy Award in 2010.', 3),
       (13,'In which year was John Lennon''s notable album "Imagine" released?', 3),
       (14, 'The song "Born in the U.S.A." (1984) is associated with which singer?', 3),
       (15, 'This Academy Award winner, for his performance in "Dallas Buyers Club," also co-founded the popular alternative rock band called 30 Seconds to Mars.', 3),
       (16, 'Which rock group was Ozzy Osbourne a member of before starting his solo career?', 3),
       (17, 'In which year was the American rock group Aerosmith inducted into the Rock and Roll Hall of Fame?', 3),
       (18, 'Which of these singers was inducted three times in Rock and Roll Hall of Fame?', 3),
       (19, 'This Canadian musician established herself as alternative rock’s foremost female vocalist with the album "Jagged Little Pill":', 3),
       (20, 'The rock band that won Grammy Awards for the track "The End Is the Beginning Is the End" for the film "Batman & Robin":', 3),

       (21, 'Which singer changed their name to an unpronounceable symbol, known as the “Love Symbol”, during a contract dispute with their record label in 1993?', 3),
       (22, 'Whose first solo album, released in June 2003, was called “Dangerously in Love”?', 3),
       (23, 'Adam Levine is the lead singer of which pop group?', 3),
       (24, 'Who had a number one hit single in both the US and the UK in 2017, with the single “Perfect”?', 3),
       (25, 'Which pop singer won a Grammy Award for Best Dance Recording for the song “Where Are U Now”?', 3),
       (26, 'Which DJ wrote and produced the hit song “We Found Love” for Rihanna?', 3),
       (27, 'Which classic 1964 single became The Temptations first U.S. number one?', 3),
       (28, 'Which song became The Beatles first U.S. number one hit single in 1964?', 3),
       (29, 'Which former member of the boyband NSYNC had a hit single with “Cry Me a River”?', 3),
       (30, 'Which band’s third album “X&Y”, released in 2005, spawned the hit singles “Fix You” and “Speed of Sound”?', 3),
       (31, 'Which girl band burst onto the scene with their debut single “Wannabe” in 1996?', 3),
       (32, 'With which girl group did Diana Ross rise to fame before she embarked on her solo career?', 3),
       (33, '"Man Eater" and "Promiscuous" were 2006 hits for which artist?', 3),
       (34, 'Who released their first debut album Love. Angel. Music. Baby in 2004?', 3),
       (35, 'Vanessa Carlton became a one-hit wonder for which 2001 song?', 3),
       (36, 'Katy Perry’s first big hit ‘I Kissed a Girl’ came out in what year?', 3),
       (37, 'How old was Britney Spears when her hit song ‘Baby One More Time’ came out in 1998?', 3),
       (38, 'Zac Hanson, the youngest brother of Hanson, was how old when the trio’s classic Mmmbop was released in 1997?', 3),
       (39, 'Which 80s star is recognised by Guinness World Records as the best-selling female recording artist of all time?', 3),
       (40, '‘Walk like an Egyptian’ was a hit song for which group in 1986?', 3),

       (41, 'Which singer famously played two live shows at Folsom Prison in January 1968?', 3),
       (42, 'In 1980, which country legend had a number one hit with “He Stopped Loving Her Today”?', 3),
       (43, 'Which country music star wrote and first recorded “I Will Always Love You”, a song which later became one of the biggest selling singles of all-time for Whitney Houston?', 3),
       (44, '“Much Too Young (To Feel This Damn Old)” was the first single released by which singer?', 3),
       (45, 'Who rose to fame with their debut single “She’s in Love with the Boy” in 1991?', 3),
       (46, 'Whose album “Not a Moment Too Soon”, featuring the number one record of the same name, was the best selling country music album of 1994?', 3),
       (47, '“There’s Your Trouble”, “Cowboy Take Me Away” and “Landslide” were hit records for which country music group?', 3),
       (48, 'Tommy beats up the Gatlin brothers after they assault his woman Becky, in which Kenny Rogers hit song?', 3),
       (49, 'Which singer, known as the “First Lady of Country Music”, is best known for the song “Stand by Your Man”?', 3),
       (50, 'Who releases the single "Space Cowboy" in 2018?', 3),
       (51, 'Who recorded two of his best-selling albums in prison?', 3),
       (52, 'Which Loretta Lynn song inspired a 1980 biographical film of the same name?', 3),
       (53, 'Which Hank Williams song was released posthumously?', 3),
       (54, 'Which singer holds the record for largest indoor concert in North America?', 3),
       (55, 'Which future country music artist witnessed one of Johnny Cash''s San Quentin concerts firsthand ... as an inmate?', 3),
       (56, 'Which Mississippi Delta queen knocked the Beatles from the top of the charts in 1967?', 3),
       (57, 'Which city is considered the Country Music Capital of the World?', 3),
       (58, 'Who originally recorded Garth Brooks'' 1991 hit "The Thunder Rolls"?', 3),
       (59, 'Which singer/songwriter reportedly landed a helicopter on Johnny Cash''s lawn to hand deliver a music demo?', 3),
       (60, 'What was Hank Williams real name?', 3),

       (61, 'What is widely regarded as the first hip hop record?', 3),
       (62, 'How many albums did The Notorious B.I.G. release before his death?', 3),
       (63, 'What name did Lil Wayne go by originally?', 3),
       (64, 'Which rapper is known for her alter egos, which include "Cookie", "Harajuku Barbie", and "Roman Zolanski"?', 3),
       (65, 'How many copies of Eminem''s debut album Infinite did he sell?', 3),
       (66, 'What was the name of Snoop Dogg''s debut album?', 3),
       (67, 'Who did Jay-Z diss in his song "Takeover"?', 3),
       (68, 'What form of vocal percussion is common in hip hop?', 3),
       (69, 'What does the "B" in Cardi B stand for?', 3),
       (70, 'Which rapper is famous for wearing parachute pants?', 3),
       (71, 'What rapper holds the world record for most words in a hit single?', 3),
       (72, 'Which rapper was controversially removed from the Billboard Hot Country Songs chart in 2019?', 3),
       (73, 'Which rapper claimed to have slept with The Notorious B.I.G.''s wife in the 1996 diss track "Hit ''Em Up"?', 3),
       (74, 'What did Snoop Dogg change his name to in 2012?', 3),
       (75, 'Who did Jay-Z marry in 2008?', 3),
       (76, 'Which dance craze is Nicki Minaj closely associated with?', 3),
       (77, 'What was the first hip hop group to win an Academy Award for best original song?', 3),
       (78, 'Which rapper has the most face tattoos?', 3),
       (79, 'Who holds the world record for longest freestyle rap?', 3),
       (80, 'Who won the first Grammy for Best Rap Performance?', 3),

       (81,'What scale does the Phrygian mode belong to?',2),
       (82, 'What is the most common time signature?', 2),
       (83, 'What is the third mode of the G Major Scale?',2),
       (84,'Assuming a guitar is in standard tuning, what note is on the 5th fret of the low E string?',2),
       (85,'Which of the following can be played over a b phrygian chord progression?',2),
       (86,'What notes are in the E minor scale?',2);
