USE master_of_music_db;

INSERT INTO answers (answer, is_correct, question_id)
VALUES ('Led Zeppelin', true, 1),
       ('AC/DC', false, 1),
       ('Lynyrd Skynyrd', false, 1),
       ('KISS', false, 1),
       ('Steven Tyler', false, 2),
       ('Jim Morrison', false, 2),
       ('Eddie Vedder', true, 2),
       ('Chris Cornell', false, 2),
       ('Zombieheads', false, 3),
       ('Deadheads', true, 3),
       ('The Devoted Dead', false, 3),
       ('The Grateful Army', false, 3),
       ('Pink Floyd', false, 4),
       ('The Eagles', true, 4),
       ('Michael Jackson', false, 4),
       ('Eric Clapton', false, 4),
       ('Red Hot Chili Peppers', false, 5),
       ('Pearl Jam', false, 5),
       ('The Smashing Pumpkins', false, 5),
       ('Nirvana', true, 5),
       ('You Give Love a Bad Name and Without Love', false, 6),
       ('Living on a Prayer and It’s My Life', true, 6),
       ('Living on a Prayer and You Give Love a Bad Name', false, 6),
       ('It’s My Life and Wanted Dead or Alive', false, 6),
       ('Jerry Lee Lewis', false, 7),
       ('Chuck Berry', false, 7),
       ('Buddy Holly', true, 7),
       ('Waylon Jennings', false, 7),
       ('AC/DC', true, 8),
       ('KISS', false, 8),
       ('Queen', false, 8),
       ('Motley Crew', false, 8),
       ('Steven Tallarico', false, 9),
       ('Vincent Damon Furnier', true, 9),
       ('Eric Patrick Clapton', false, 9),
       ('Gordon Sumner', false, 9),
       ('Slipknot', false, 10),
       ('Metallica', true, 10),
       ('Led Zeppelin', false, 10),
       ('Linkin Park', false, 10),
       ('Anthrax', false, 11),
       ('Slayer', false, 11),
       ('Exodus', false, 11),
       ('Pearl Jam', true, 11),
       ('Highway to Hell', false, 12),
       ('Bring the Noise', false, 12),
       ('High Hopes', false, 12),
       ('War Machine', true, 12),
       ('1990', false, 13),
       ('1971', true, 13),
       ('1980', false, 13),
       ('1960', false, 13),
       ('Steven Van Zandt', false, 14),
       ('Clarence Clemons', false, 14),
       ('Bruce Springsteen', true, 14),
       ('Billy Joel', false, 14),
       ('Russell Crowe', false, 15),
       ('Jack Black', false, 15),
       ('Jared Leto', true, 15),
       ('Ryan Gosling', false, 15),
       ('Heartbreakers', false, 16),
       ('Black Sabbath', true, 16),
       ('Steely Dan', false, 16),
       ('Def Leppard', false, 16),
       ('1975', false, 17),
       ('1995', false, 17),
       ('2011', false, 17),
       ('2001', true, 17),
       ('John Lennon', false, 18),
       ('Ginger Baker', false, 18),
       ('Eric Clapton', true, 18),
       ('Elvis Presley', false, 18),
       ('Patti Smith', false, 19),
       ('Alanis Morissette', true, 19),
       ('Nancy Wilson', false, 19),
       ('Suzi Quatro', false, 19),
       ('Green Day', false, 20),
       ('Evanescence', false, 20),
       ('INXS', false, 20),
       ('Smashing Pumpkins', true, 20),

       ('Michael Jackson', false, 21),
       ('Lenny Kravitz', false, 21),
       ('Prince', true, 21),
       ('Billy Joel', false, 21),
       ('Beyonce', true, 22),
       ('Monica', false, 22),
       ('Avril Lavigne', false, 22),
       ('Brandy', false, 22),
       ('The Script', false, 23),
       ('OneRepublic', false, 23),
       ('The Fray', false, 23),
       ('Maroon 5', true, 23),
       ('Taylor Swift', false, 24),
       ('Sam Smith', false, 24),
       ('Ed Sheeran', true, 24),
       ('Shawn Mendes', false, 24),
       ('Justin Timberlake', false, 25),
       ('Justin Bieber', true, 25),
       ('Selena Gomez', false, 25),
       ('Miley Cyrus', false, 25),
       ('Calvin Harris', true, 26),
       ('Martin Garrix', false, 26),
       ('David Guetta', false, 26),
       ('Avicii', false, 26),
       ('Papa Was a Rollin Stone', false, 27),
       ('My Girl', true, 27),
       ('Get Ready', false, 27),
       ('Ain''t to Proud To Beg', false, 27),
       ('Let it Be', false, 28),
       ('Here Comes the Sun', false, 28),
       ('Hey Jude', false, 28),
       ('I Want to Hold Your Hand', true, 28),
       ('Nick Lachey', false, 29),
       ('Nick Carter', false, 29),
       ('Lance Bass', false, 29),
       ('Justin Timberlake', true, 29),
       ('OneRepublic', false, 30),
       ('Imagine Dragons', false, 30),
       ('Coldplay', true, 30),
       ('The Chainsmokers', false, 30),
       ('Spice Girls', true, 31),
       ('Destiny''s Child', false, 31),
       ('The Pussycat Dolls', false, 31),
       ('S Club 7', false, 31),
       ('The Marvelettes', false, 32),
       ('The Supremes', true, 32),
       ('Martha & The Vandellas', false, 32),
       ('The Velvelettes', false, 32),
       ('Natalie Imbruglia', false, 33),
       ('Avril Lavigne', false, 33),
       ('Nelly Furtado', true, 33),
       ('Britney Spears', false, 33),
       ('Gwen Stefani', true, 34),
       ('Kelly Clarkson', false, 34),
       ('P!nk', false, 34),
       ('Jennifer Lopez', false, 34),
       ('A Thousand Years', false, 35),
       ('Someone Like You', false, 35),
       ('Ordinary Day', false, 35),
       ('A Thousand Miles', true, 35),
       ('2009', false, 36),
       ('2007', false, 36),
       ('2008', true, 36),
       ('2006', false, 36),
       ('16', false, 37),
       ('18', false, 37),
       ('17', true, 37),
       ('15', false, 37),
       ('13', false, 38),
       ('11', true, 38),
       ('15', false, 38),
       ('14', false, 38),
       ('Madonna', true, 39),
       ('Diana Ross', false, 39),
       ('Annie Lennox', false, 39),
       ('Gloria Estefan', false, 39),
       ('Bananarama', false, 40),
       ('The Runaways', false, 40),
       ('The Bangles', true, 40),
       ('The Go-Go''s', false, 40),

       ('Johnny Cash', true, 41),
       ('Merle Haggard', false, 41),
       ('Kris Kristofferson', false, 41),
       ('Willie Nelson', false, 41),
       ('Conway Twitty', false, 42),
       ('Randy Travis', false, 42),
       ('George Jones', true, 42),
       ('Waylon Jennings', false, 42),
       ('Reba McEntire', false, 43),
       ('Dolly Parton', true, 43),
       ('Loretta Lynn', false, 43),
       ('Tanya Tucker', false, 43),
       ('George Strait', false, 44),
       ('Garth Brooks', true, 44),
       ('Alan Jackson', false, 44),
       ('Tim McGraw', false, 44),
       ('Reba McEntire', false, 45),
       ('Carrie Underwood', false, 45),
       ('Martina McBride', false, 45),
       ('Trisha Yearwood', true, 45),
       ('Faith Hill', false, 46),
       ('Tim McGraw', true, 46),
       ('Keith Urban', false, 46),
       ('Brad Paisley', false, 46),
       ('Lady A', false, 47),
       ('Asleep at the Wheel', false, 47),
       ('Dixie Chicks', true, 47),
       ('Little Big Town', false, 47),
       ('Coward of the County', true, 48),
       ('The Gambler', false, 48),
       ('She Believes In Me', false, 48),
       ('Lucille', false, 48),
       ('Loretta Lynn', false, 49),
       ('Tammy Wynette', true, 49),
       ('Patsy Cline', false, 49),
       ('Dolly Parton', false, 49),
       ('Miranda Lambert', false, 50),
       ('Kacey Musgraves', true, 50),
       ('Kelsea Ballerini', false, 50),
       ('Brandy Clark', false, 50),
       ('Hank Williams', false, 51),
       ('Randy Travis', false, 51),
       ('Merle Haggard', false, 51),
       ('Johnny Cash', true, 51),
       ('Entertainer of the Year', false, 52),
       ('Honky Tonk Heroes', false, 52),
       ('Fist City', false, 52),
       ('Coal Miner''s Daughter', true, 52),
       ('Hey, Good Lookin''', false, 53),
       ('Your Cheatin'' Heart', true, 53),
       ('Honky Tonk Blues', false, 53),
       ('Never Again (Will I Knock On Your Door)', false, 53),
       ('Tim McGraw', false, 54),
       ('Garth Brooks', false, 54),
       ('George Strait', true, 54),
       ('Shania Twain', false, 54),
       ('Charley Pride', false, 55),
       ('Ronnie Milsap', false, 55),
       ('Merle Haggard', true, 55),
       ('Waylon Jennings', false, 55),
       ('Patsy Cline', false, 56),
       ('Bobbie Gentry', true, 56),
       ('Norma Jean', false, 56),
       ('Loretta Lynn', false, 56),
       ('Memphis', false, 57),
       ('Louisville', false, 57),
       ('Denver', false, 57),
       ('Nashville', true, 57),
       ('Kenny Rogers', false, 58),
       ('Dwight Yoakam', false, 58),
       ('Tanya Tucker', true, 58),
       ('Reba McEntire', false, 58),
       ('Glen Campbell', false, 59),
       ('Kris Kristofferson', true, 59),
       ('Kenny Rogers', false, 59),
       ('Charlie Daniels', false, 59),
       ('Hudson', false, 60),
       ('Holden', false, 60),
       ('Hector', false, 60),
       ('Hiram', true, 60),

       ('8th Wonder', false, 61),
       ('Rappin'' Blow Part 2', false, 61),
       ('Rapper''s Delight', true, 61),
       ('Go-Go Crankin', false, 61),
       ('1', true, 62),
       ('3', false, 62),
       ('2', false, 62),
       ('4', false, 62),
       ('Lil Daddy', false, 63),
       ('Baby Daddy', false, 63),
       ('Pimp Daddy', false, 63),
       ('Shrimp Daddy', true, 63),
       ('Missy Elliott', false, 64),
       ('Cardi B', false, 64),
       ('Nicki Minaj', true, 64),
       ('Lil Kim', false, 64),
       ('10,000', false, 65),
       ('1,000', true, 65),
       ('1,000,000', false, 65),
       ('100,000', false, 65),
       ('Doggystyle', true, 66),
       ('Doggumentary', false, 66),
       ('The Doggfather', false, 66),
       ('No Limit Top Dogg', false, 66),
       ('Meek Mill', false, 67),
       ('Nas', true, 67),
       ('Nicki Minaj', false, 67),
       ('Drake', false, 67),
       ('Mouthdrumming', false, 68),
       ('Chopbusting', false, 68),
       ('Freestyling', false, 68),
       ('Beatboxing', true, 68),
       ('Bazookas', false, 69),
       ('Beatboxer', false, 69),
       ('Bikini', false, 69),
       ('Bacardi', true, 69),
       ('Ice Cube', false, 70),
       ('Snoop Dogg', false, 70),
       ('MC Hammer', true, 70),
       ('Lauryn Hill', false, 70),
       ('Eminem', true, 71),
       ('Busta Rhymes', false, 71),
       ('50 Cent', false, 71),
       ('Kanye West', false, 71),
       ('Blanco Brown', false, 72),
       ('Lil Nas X', true, 72),
       ('Nelly', false, 72),
       ('Kid Rock', false, 72),
       ('Ice Cube', false, 73),
       ('Snoop Dogg', false, 73),
       ('2Pac', true, 73),
       ('Dr. Dre', false, 73),
       ('Snoop Lion', true, 74),
       ('Snoop Vulture', false, 74),
       ('Snoop Dragon', false, 74),
       ('An Unpronounceable Symbol', false, 74),
       ('Rihanna', false, 75),
       ('Foxy Brown', false, 75),
       ('Missy Elliott', false, 75),
       ('Beyonce', true, 75),
       ('Whip/Nae Nae', false, 76),
       ('The Floss', false, 76),
       ('Twerking', true, 76),
       ('Shooting', false, 76),
       ('Fugees', false, 77),
       ('Salt-N-Pepa', false, 77),
       ('Three 6 Mafia', true, 77),
       ('Wu-Tang-Clan', false, 77),
       ('Trippie Red', false, 78),
       ('Lil Wayne', true, 78),
       ('Post Malone', false, 78),
       ('Gucci Mane', false, 78),
       ('FRZY', true, 79),
       ('M-Eighty', false, 79),
       ('KJ52', false, 79),
       ('Chiddy', false, 79),
       ('LL Cool J', false, 80),
       ('Kool Moe Dee', false, 80),
       ('DJ Jazzy Jeff & The Fresh Prince', true, 80),
       ('Young MC', false, 80),

       ('Harmonic Minor',true,81),
       ('Diminished',false,81),
       ('Pentatonic',false,81),
       ('Major',false,81),
       ('4/4',true,82),
       ('7/8',false,82),
       ('5/4',false,82),
       ('6/4',false,82),
       ('Phrygian',true,83),
       ('Dorian',false,83),
       ('Aeolian',false,83),
       ('Mixolydian',false,83),
       ('B',false,84),
       ('F',false,84),
       ('B flat',false,84),
       ('A',true,84),
       ('E major scale',false,85),
       ('E phrygian dominant',false,85),
       ('E Hungarian Minor',true,85),
       ('G Minor',false,85),
       ('E,E,F,D,A,B,Octave',false,86),
       ('E,F,A,A,B,B,E',false,86),
       ('E,F,G,A,B,C,D',true,86),
       ('G,G,A,B,B,C,Octave',false,86);